Wrappers return a list of messages instead of a single message
decidim/decidim-bulletin-board pull request #129
Opened 2021-02-26 15:37 UTC by txus

* Depends on https://github.com/decidim/decidim-electionguard/pull/11

2021-03-01 15:01 UTC, leio10 requested changes
Nice!! 😍 👏

2021-03-01 15:01 UTC, leio10 commented on decidim-bulletin_board-app/app/commands/process_key_ceremony_step.rb
> +    if response_log_entries && response_log_entries.any? { |le| le.message_identifier.type == "end_key_ceremony" }
I guess that here and in the tally we can assume that the `end_...` will be the last response, right? Even with that, maybe this approach is healthier. 🤔

2021-03-02 14:23 UTC, beagleknight approved these changes

2021-03-02 14:42 UTC, leio10 approved these changes
👍

2021-03-02 14:44 UTC, merged