Adds ENV vars for configuring the BB server
decidim/decidim-bulletin-board pull request #310
Opened 2023-12-07 16:24 UTC by microstudi

fixes #287 
supersedes #301

2023-12-12 14:20 UTC, andreslucena requested changes
Two small changes, let me know if you prefer that I handle the rubocop update

2023-12-12 14:20 UTC, andreslucena commented on bulletin_board/server/.rubocop.yml
Can you leave it out with `develop` and bump the rubocop version 🙏🏽 ?

2023-12-12 14:20 UTC, andreslucena commented on bulletin_board/server/spec/commands/create_election_spec.rb
> +    context "when HOURS_BEFORE_CREATE_ELECTION is set" do
As we're not doing the test with the ENV VAR, I'd prefer to not reference to that in the example title

```suggestion
    context "when the `hours before` the election creation is set" do
```

2023-12-13 12:32 UTC, microstudi commented on bulletin_board/server/.rubocop.yml
ok done. this forces to update many other files though

2023-12-13 13:24 UTC, andreslucena commented
@microstudi there's a failing spec, can you check it out please?

2023-12-13 15:21 UTC, microstudi commented
All done @andreslucena !

2023-12-13 15:54 UTC, andreslucena commented on bulletin_board/server/.rubocop.yml
> +
```suggestion
```

2023-12-14 09:49 UTC, andreslucena approved these changes
As we've talked offline, you'll fix the empty line in the next PR, so I'll merge this one

2023-12-14 09:49 UTC, merged