fix & documentate verifier
decidim/decidim-bulletin-board pull request #311
Opened 2023-12-12 14:19 UTC by microstudi

2024-01-09 11:35 UTC, andreslucena requested changes
I just checked the installation instructions. For the moment it seems much better than what we have. There's just a minor detail to fix and we can merge this

2024-01-09 11:35 UTC, andreslucena commented on verifier/README.md
> +node src/index.js --help
I think this doesn't work:
```console
$ node src/index.js --help
[Error: ENOENT: no such file or directory, access '--help'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '--help'
}
```

2024-01-09 13:14 UTC, microstudi commented on verifier/README.md
> +node src/index.js --help
Because it needed to be run inside the "verify" folder.
I've update the instructions

2024-01-11 12:37 UTC, andreslucena approved these changes

2024-01-11 12:37 UTC, andreslucena commented on verifier/README.md
> +node src/index.js --help
Confirmed that it was fixed

2024-01-11 12:55 UTC, merged