Document README files
decidim/decidim-bulletin-board pull request #312
Opened 2023-12-20 11:50 UTC by microstudi

2024-01-09 10:50 UTC, andreslucena requested changes
Great improvement, I only have a few minor details and this is ready

2024-01-09 10:50 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
>  Add this line to your application's Gemfile:
```suggestion
Run this command to add the gem to your Gemfile:
```

2024-01-09 10:50 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
>  ```ruby
```suggestion
```console
```

2024-01-09 10:50 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
> +gem 'decidim-bulletin_board', "~> 0.24.4"
```suggestion
bundle add decidim-bulletin_board
```

2024-01-09 10:50 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
> +
```suggestion
```

2024-01-09 10:50 UTC, andreslucena commented on bulletin_board/server/README.md
> +The Bulletin Board is intended to use alongside a Decidim installation. It's main purpose is to provide a GraphQL interface to a secure, auditable and verifiable voting system. This is currently achi
```suggestion
The Bulletin Board is intended to use alongside a Decidim installation. Its main purpose is to provide a GraphQL interface to a secure, auditable and verifiable voting system. This is currently achieved by using the [ElectionGuard python implementation](https://github.com/microsoft/electionguard-python), developed by Microsoft. So this server acts as a [wrapper to the ElectionGuard python code](../../voting_schemes/electionguard/python-wrapper).
```

2024-01-09 13:06 UTC, microstudi commented
Changes applied @andreslucena

2024-01-11 12:58 UTC, andreslucena requested changes
A couple more details and we're good

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
>  And then execute:
```suggestion
```

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
```suggestion
```

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
> +```
```suggestion
```

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
```suggestion
```

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
> +This gem provides a collection of commands to interact with such API using Ruby. Mainly for it's use in a backend service.
```suggestion
This gem provides a collection of commands to interact with such API using Ruby, mainly for its use in a backend service.
```

2024-01-11 12:58 UTC, andreslucena commented on bulletin_board/ruby-client/README.md
>  And then execute:
No need to run `bundle install` if we're doing `bundle add `

2024-01-11 14:52 UTC, andreslucena approved these changes

2024-01-11 14:52 UTC, andreslucena commented
There's a failing spec for a linter but that's already happening in the `develop` branch, so I'm merging this

2024-01-11 14:53 UTC, merged